# Generated by Django 3.0.8 on 2020-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='compID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
