# Generated by Django 3.0.8 on 2020-09-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20200907_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.Worker'),
        ),
    ]
